config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :games, param: :name, shallow: true, only: [:index, :create, :show] do
    resources :players, only: [:index, :create, :show, :new] do
      resources :words, only: [:index, :create, :show, :new]
    end
    resources :rounds, only: [:create]
    resources :turns, only: [:create]
  end

  get '/:name/join', to: "games#join"
  get '/:name/results', to: "games#results", as: :game_results
  post '/join', to: "games#join"

  get '/:name', to: "rounds#play", as: :play_round
  post '/:name/next_turn/:id/', to: "rounds#next_turn", as: :next_turn

  get '/:name/play/', to: "turns#play", as: :play_turn
  post '/:name/next_word/:id/', to: "turns#next_word", as: :next_word
  post '/:name/end_turn/:id/', to: "turns#end", as: :end_turn

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :round
  belongs_to :player
  belongs_to :game
  has_many :plays, dependent: :destroy
  has_many :words, through: :plays

  # length in seconds (add a couple of seconds to account for load time)
  def time_limit
    62
  end

  def new?
    plays.empty?
  end

  def time_elapsed
    Time.now - plays.first.created_at
  end

  def ms_remaining
    (1000 * time_remaining).ceil
  end

  def seconds_remaining
    t = (time_remaining).ceil
    t <= 0 ? 0 : t
  end

  def time_remaining
    time_limit - time_elapsed
  end

  def finished?
    next_word.nil? || !plays.empty? && time_remaining <= 0
  end

  def next_word
    (game.words - played_words).shuffle.first
  end

  def finish
    plays.last.finish(false)
  end

  def played_words
    complete = round.plays.complete.order(:duration)
    complete.empty? ? [] : complete.map(&:word)
  end

  def finish_word(complete=nil)
    if p = plays.last
      p.finish(0 < time_remaining)
    end
  end

  def current_word
    plays.last.word
  end

  def words_remaining
    round.words_remaining
  end

  def score
    plays.complete.map(&:score)
  end

  def play_word
    finish_word

    if w = next_word
      plays.create(round: round, player: player, word: w, index: plays.size)
    end
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  def create
    @game = Game.find_by_name(params[:game_name].upcase)
    @round = @game.current_round
    @round.start_turn
    redirect_to play_turn_path @game
  end

  def end
    @turn = Turn.find(params[:id])
    @turn.finish
    
    redirect_to play_turn_path @turn.game
  end

  def next_word
    @turn = Turn.find(params[:id])
    @turn.play_word

    redirect_to play_turn_path @turn.game
  end

  def play
    @game = Game.find_by_name(params[:name])
    @turn = @game.current_turn
    if @turn.new?
      render "_start"
    elsif @turn.finished?
      render "_results"
    else
      render "_card"
    end
  end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_card.html.slim
h1= @turn.current_word.name

script
  |window.setTimeout(function() { document.querySelector('#end-turn').submit() }, #{@turn.ms_remaining}) 

p Time left: #{@turn.seconds_remaining} seconds
- if @turn.words_remaining > 1
  p #{@turn.words_remaining - 1} cards left
- else
  p Last Card!
p Current Player: #{@turn.player.name}

= render "games/team_totals"

= form_with url: next_word_path(@game, @turn) do |form|
  = form.submit "Next Word"

= form_with id: 'end-turn', url: end_turn_path(@game, @turn)

app/views/turns/_new.html.slim
= form_with scope: :round, url: game_turns_path(@game) do |form|
  = form.submit "Next"

app/views/turns/_results.html.slim
h1 Results

h3 Words guessed:
ul
  - @turn.plays.complete.each do |play|
    li
      strong= play.word.name
      span= play.duration
      = render partial: "score", locals: { play: play, score: play.score }

p = @turn.player.points
p
  'Team #{@turn.player.team_number} score:
  = @turn.player.team_score
p= link_to "Next", play_round_path(@turn.game)

app/views/turns/_score.html.slim
- if score[:speed_bonus] || score[:word_bonus]
  span<> 
   |(
  - if score[:speed_bonus]
    '+
    span.speed-bonus=> score[:speed_bonus]
  - if score[:word_bonus]
    '+
    span.word-bonus=> score[:word_bonus]
  span> )

app/views/turns/_start.html.slim
h1 Get ready, #{@game.current_turn.player.name} on Team #{@game.current_turn.player.team_number}

= form_with url: next_word_path(@game, @turn) do |form|
  = form.submit "Start"

app/views/turns/play.html.slim
h1 playing

= @turn.current_word.name