config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :games, param: :name, shallow: true, only: [:index, :create, :show] do
    resources :players, only: [:index, :create, :show, :new] do
      resources :words, only: [:index, :create, :show, :new]
    end
    resources :rounds, only: [:create]
    resources :turns, only: [:create]
  end

  get '/:name/join', to: "games#join"
  get '/:name/results', to: "games#results", as: :game_results
  post '/join', to: "games#join"

  get '/:name', to: "rounds#play", as: :play_round
  post '/:name/next_turn/:id/', to: "rounds#next_turn", as: :next_turn

  get '/:name/play/', to: "turns#play", as: :play_turn
  post '/:name/next_word/:id/', to: "turns#next_word", as: :next_word
  post '/:name/end_turn/:id/', to: "turns#end", as: :end_turn

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :rounds, dependent: :destroy
  has_many :turns, dependent: :destroy
  has_many :words, through: :players
  has_many :plays, through: :rounds

  validates :name, presence: true,
                   uniqueness: true,
                    length: { minimum: 5, maximum: 20 }

  def team_count
    2
  end

  def round_count
    3
  end

  def player_word_limit
    6
  end

  def minimum_players
    4
  end

  def to_param 
    name
  end

  def game_name
    name
  end

  def teams
    players.group_by(&:team)
  end

  def ready?
    # Enough players here and all players are ready
    # (they have entered all their words)
    enough_players? && players_ready?
  end

  def players_ready?
    players.reject(&:ready?).empty?
  end

  # Game was created 5 hours ago
  def expired?
    created_at.advance(hours: 5) < Time.now
  end

  def enough_players?
    players.size >= minimum_players
  end

  def needed_players
    minimum_players - players.size
  end

  def started?
    !rounds.empty?
  end

  def players_played
    turns.empty? ? turns : turns.map(&:player)
  end

  def next_team_id
    players_played.size % team_count
  end

  def team_turns(team)
    if players_played.empty?
      0
    else
      players_played.select { |p| p.team == team }.size
    end
  end

  def next_player
    team_id = next_team_id
    team_players = teams[team_id]

    # How many turns for this team?
    plays = team_turns(team_id)

    team_players[plays % team_players.size]
  end

  def start
    current_round || new_round
  end

  def current_round
    rounds.last
  end

  def current_turn
    turns.last
  end

  def current_player
    current_turn.player
  end

  def new_round
    rounds.create()
  end

  def team_scores
    t = {}
    teams.each do |team, pls|
      t[team] = pls.map(&:points).sum
    end

    t
  end

  def fastest_play
    plays.complete.order(:duration).first
  end

  def hardest_word
    words.sort_by(&:duration).last
  end

  def easiest_word
    words.sort_by(&:duration).first
  end

  def easiest_writer
    players.sort_by(&:word_speed).first
  end

  def hardest_writer
    players.sort_by(&:word_speed).last
  end

  def best_actor
    rounds[1].best_player
  end

  def self.expired_games
    all.select(&:expired?)
  end

  # Destroy expired games
  def self.scrub_games
    expired_games.map(&:destroy)
  end

  def self.short_code
    source = [*?A..?Z] - ['O']
    short = ''
    5.times { short << source.sample.to_s }
    short
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @game = Game.new name: Game.short_code, one_device: game_params[:one_device]

    while !@game.save do
      @game.name = Game.short_code
    end

    redirect_to new_game_player_path(@game)
  end

  def index
    @games = Game.all
  end

  def show
    @game = Game.find_by_name(params[:name])
  end

  def destroy
    Game.find_by_name(params[:name]).destroy
    redirect_to games_path end

  def join
    @game = Game.find_by_name(params[:name].upcase)

    if @game
      unless @game.started?
        redirect_to new_game_player_path(@game)
      else
        flash[:info] = "Sorry, you can't join a game which has already begun. Start a new game?"
        redirect_to "/"
      end
    else
      # TODO: 404 redirection
      redirect_to "/"
    end
  end

  def start
    @game = Game.find_by_name(params[:name].upcase)

    if @game.start
      redirect_to new_game_player_path(@game)
    else
      # TODO: 404 redirection
      redirect_to game_path
    end

  end

  def results
    @game = Game.find_by_name(params[:name])
  end

  private

  def game_params
    params.require(:game).permit(:one_device)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.slim
= form_with scope: :game, url: games_path, local: true do |form|
  = form.hidden_field :name, value: short_code
  = form.submit "New Game"

app/views/games/_join.html.slim
= form_with url: join_path do |form|
  = form.text_field :name
  = primary_button "Join"

app/views/games/_new.html.slim
= form_with scope: :game, url: games_path do |form|
  = form.hidden_field :one_device, value: true
  = primary_button "Pass & Play"

= form_with scope: :game, url: games_path do |form|
  = form.hidden_field :one_device, value: false
  = primary_button 'Multi Screen'

app/views/games/_start.html.slim
= form_with scope: :round, url: game_rounds_path(@game) do |form|
  = form.submit "Start Game"

app/views/games/_team_totals.html.slim
p Scores:
- @game.team_scores.each do |team, score|
  strong> Team #{team + 1}:
  = score
  br

app/views/games/index.html.slim
h1 All the Games!
ul
  - @games.each do |game|
    li
      => link_to "#{game.name} (#{game.players.size})", game
      ' - 
      = link_to "delete", game, method: "delete"
= render "new"

app/views/games/join.html.slim
h1 Welcome to WordRush
= render 'players/form'

app/views/games/new.html.slim
h1 New Game
= render "new"

app/views/games/results.html.slim
h1 Results

- @game.teams.each do |team, players|
  h5 Team #{team + 1} (#{@game.team_scores[team]})
  ul
    - players.each do |player|
      li
        |#{player.name} (#{player.points})

hr

h4 Easiest Writer
p= @game.easiest_writer.name

hr

h4 Hardest Writer
p= @game.hardest_writer.name

hr

h4 Hardest word
p= @game.hardest_word.name
ul
  - @game.hardest_word.plays.complete.each do |play|
    li
      => play.player.name
      |(#{play.duration})

hr

h4 Easiest word
p= @game.easiest_word.name
ul
  - @game.easiest_word.plays.complete.each do |play|
    li
      => play.player.name
      |(#{play.duration})

hr

h4 Best Player by round
ul
  - @game.rounds.each do |round|
    li
      strong=> round.number
      span= round.best_player.name

app/views/games/show.html.slim
- unless @game.enough_players?
  p You need #{@game.needed_players} more #{"player".pluralize(@game.needed_players)} to begin.

- unless @game.players.empty?
  = render 'players/list'

- if @game.one_device
  p= link_to "Add a player", new_game_player_path(@game)

- if @game.ready?
  = render "games/start"